version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: dm_postgres
    environment:
      POSTGRES_USER: porto
      POSTGRES_PASSWORD: porto_password
      POSTGRES_DB: porto_logistica
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: dm_adminer
    ports:
      - "8080:8080"

  data-module:
    build: .
    container_name: data_module
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://porto:porto_password@postgres:5432/porto_logistica
      KAFKA_HOST: kafka:9092
    ports:
      - "8000:8000"

volumes:
  pgdata:
